## Points Chart 2022 Testing Data

In [24]:
import sys

In [25]:
import pickle
import sqlite3
import numpy as np

import pandas as pd

In [26]:
from bokeh.io import output_notebook

In [27]:
output_notebook()

In [28]:
sys.path

['/Users/nehamuramalla/pythonrobotics/scouting2022/experiments',
 '/Users/nehamuramalla/pythonrobotics/scouting2022/scouter',
 '/Users/nehamuramalla/pythonrobotics/scouting2022',
 '/Users/nehamuramalla/scouting2020',
 '/opt/anaconda3/lib/python38.zip',
 '/opt/anaconda3/lib/python3.8',
 '/opt/anaconda3/lib/python3.8/lib-dynload',
 '',
 '/opt/anaconda3/lib/python3.8/site-packages',
 '/opt/anaconda3/lib/python3.8/site-packages/aeosa',
 '/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions',
 '/Users/nehamuramalla/.ipython',
 '/Users/nehamuramalla/pythonrobotics/scouting2022/scouter',
 '/Users/nehamuramalla/pythonrobotics/scouting2022/scouter']

In [29]:
sys.path.append('/Users/nehamuramalla/pythonrobotics/scouting2022/scouter')

In [30]:
# lower, upper, hanger end
# auto - lower 2, auto - upper 4
# teleop - lower 1, upper - 2

In [38]:
import viewer.app.data as data

In [41]:
measures = data.get_data()[0] 
matches = data.get_data()[1]

In [42]:
measures

,match,measure1,measure2,measure_type,phase,task,team_number
0,qm1,left,-1,categorical,auto,start_pos,frc1294
1,qm1,1,-1,count,auto,pickup_field,frc1294
10,qm1,2,-1,count,tele,pickup-field,frc4512
100,qm1,0,-1,count,endgame,penalty_count,frc4915
1000,qm8,0,-1,count,endgame,penalty_count,frc949
...,...,...,...,...,...,...,...
995,qm8,0,0,count,auto,hp,frc949
996,qm8,0,-1,count,endgame,hangar_level_end,frc949
997,qm8,false,-1,boolean,endgame,fall_over,frc949
998,qm8,0,-1,count,endgame,hangar_level_start,frc949
999,qm8,0,0,count,tele,lower,frc949

In [43]:
matches

    alliance match           match_time  station team_number
0       blue   qm1  2022-03-19 21:15:00        1     frc4915
1       blue   qm1  2022-03-19 21:15:00        2     frc1294
10       red   qm2  2022-03-19 21:25:00        2     frc4579
100      red  qm17  2022-03-19 23:45:00        2     frc2980
101      red  qm17  2022-03-19 23:45:00        3     frc4180
..       ...   ...                  ...      ...         ...
95       red  qm16  2022-03-19 23:37:30        3     frc2929
96      blue  qm17  2022-03-19 23:45:00        1     frc4469
97      blue  qm17  2022-03-19 23:45:00        2     frc4911
98      blue  qm17  2022-03-19 23:45:00        3     frc3786
99       red  qm17  2022-03-19 23:45:00        1     frc3049

[372 rows x 5 columns]

In [44]:
qmmatch = matches[matches.match.str.startswith('qm') == True]
lmatch = qmmatch[qmmatch.match < lm]
qmmatch

NameError: name 'lm' is not defined

In [45]:
lmatch

NameError: name 'lmatch' is not defined

In [46]:
last_row = measures.iloc[-1]
lm = last_row[0]
lm

'qm8'

In [47]:
measures.head(20)

,match,measure1,measure2,measure_type,phase,task,team_number
0,qm1,left,-1,categorical,auto,start_pos,frc1294
1,qm1,1,-1,count,auto,pickup_field,frc1294
10,qm1,2,-1,count,tele,pickup-field,frc4512
100,qm1,0,-1,count,endgame,penalty_count,frc4915
1000,qm8,0,-1,count,endgame,penalty_count,frc949
1001,qm8,0,-1,count,tele,pickup-field,frc949
1002,qm8,0,-1,count,tele,pickup-terminal,frc949
1003,qm8,0,-1,count,auto,pickup_field,frc949
1004,qm8,0,-1,count,auto,pickup_terminal,frc949
1005,qm8,false,-1,boolean,endgame,temp_disabled,frc949
1006,qm8,0,0,count,auto,upper,frc949
1007,qm8,0,0,count,tele,upper,frc949
1008,qm9,left,-1,categorical,auto,start_pos,frc4512
1009,qm9,right,-1,categorical,auto,start_pos,frc4911
101,qm1,0,-1,count,auto,pickup_field,frc4915
1010,qm9,center,-1,categorical,auto,start_pos,frc5683
1011,qm9,center,-1,categorical,auto,start_pos,frc488
1012,qm9,true,-1,boolean,auto,start_cargo,frc488
1013,qm9,right,-1,categorical,auto,start_pos,frc7627
1014,qm9,left,-1,categorical,auto,start_pos,frc4682

In [48]:
# filter tasks to only upper and lower
# filtered_measures = measures[(measures.task == "upper") | (measures.task == "lower")]
filtered_measures = measures[measures.task.isin(['upper','lower'])].copy()

In [49]:
filtered_measures.measure1 = pd.to_numeric(filtered_measures.measure1)
filtered_measures

     match  measure1 measure2 measure_type phase   task team_number
1006   qm8         0        0        count  auto  upper      frc949
1007   qm8         0        0        count  tele  upper      frc949
1020   qm9         1        0        count  auto  upper     frc4512
1021   qm9         2        0        count  auto  lower     frc7627
1023   qm9         1        0        count  auto  lower     frc5683
...    ...       ...      ...          ...   ...    ...         ...
98     qm1         0        0        count  tele  lower     frc4915
980    qm8         0        0        count  auto  upper     frc4915
99     qm1         0        0        count  auto  lower     frc4915
992    qm8         0        0        count  auto  upper     frc2928
999    qm8         0        0        count  tele  lower      frc949

[1457 rows x 7 columns]

In [50]:
fm_group = filtered_measures.groupby(['team_number','task','phase'])
df = fm_group.agg({"measure1": "mean"})

In [51]:
df

                                        measure1
team_number                task  phase
TypeError: Failed to fetch upper auto   1.000000
                                 tele   2.000000
frc1294                    lower auto   0.000000
                                 tele   0.000000
                           upper auto   0.727273
...                                          ...
frc948                     upper tele   0.000000
frc949                     lower auto   0.583333
                                 tele   1.500000
                           upper auto   0.000000
                                 tele   0.000000

[126 rows x 1 columns]

In [52]:
pt = filtered_measures.pivot_table("measure1", ["team_number","task"], "phase") 
pt = pt.reset_index() 
pt

phase                 team_number   task      auto      tele
0      TypeError: Failed to fetch  upper  1.000000  2.000000
1                         frc1294  lower  0.000000  0.000000
2                         frc1294  upper  0.727273  2.090909
3                         frc1318  lower  0.000000  0.545455
4                         frc1318  upper  0.363636  4.545455
..                            ...    ...       ...       ...
58                        frc7627  upper  0.000000  0.000000
59                         frc948  lower  0.416667  5.500000
60                         frc948  upper  0.000000  0.000000
61                         frc949  lower  0.583333  1.500000
62                         frc949  upper  0.000000  0.000000

[63 rows x 4 columns]

In [69]:
pt

phase                 team_number   task      auto      tele
0      TypeError: Failed to fetch  upper  1.000000  2.000000
1                         frc1294  lower  0.000000  0.000000
2                         frc1294  upper  0.727273  2.090909
3                         frc1318  lower  0.000000  0.545455
4                         frc1318  upper  0.363636  4.545455
..                            ...    ...       ...       ...
58                        frc7627  upper  0.000000  0.000000
59                         frc948  lower  0.416667  5.500000
60                         frc948  upper  0.000000  0.000000
61                         frc949  lower  0.583333  1.500000
62                         frc949  upper  0.000000  0.000000

[63 rows x 4 columns]

In [70]:
lower_auto = pt[pt['task'] == 'lower']['auto']
upper_auto = pt[pt['task'] == 'upper']['auto']
lower_tele = pt[pt['task'] == 'lower']['tele']
upper_tele = pt[pt['task'] == 'upper']['tele']
team = pt['team_number'].unique()

In [71]:
team

array(['TypeError: Failed to fetch', 'frc1294', 'frc1318', 'frc1778',
       'frc1899', 'frc1983', 'frc2412', 'frc2928', 'frc2929', 'frc2980',
       'frc3049', 'frc3218', 'frc3681', 'frc3786', 'frc4173', 'frc4180',
       'frc4205', 'frc4309', 'frc4469', 'frc4512', 'frc4579', 'frc4682',
       'frc488', 'frc4911', 'frc4915', 'frc492', 'frc5588', 'frc5683',
       'frc5827', 'frc7627', 'frc948', 'frc949'], dtype=object)

In [72]:
newdf = pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)
newdf[['team','upper_auto', 'lower_auto', 'upper_tele', 'lower_tele']] = [team, upper_auto, lower_auto, upper_tele, lower_tele]

KeyError: "None of [Index(['team', 'upper_auto', 'lower_auto', 'upper_tele', 'lower_tele'], dtype='object')] are in the [columns]"

In [57]:
bob = ["upper_auto", 'lower_auto', 'upper_tele', 'lower_tele']
#newdf.loc[newdfi == "NaN", "upper_auto"] = 0
# newdf.loc[newdf["upper_auto"] == 'NaN', "upper_auto"] = 0
for i in bob:
    newdf[i] = newdf[i].fillna(0)

KeyError: 'upper_auto'

In [58]:
newdf.head(5)

Empty DataFrame
Columns: []
Index: []

In [59]:
newdf

Empty DataFrame
Columns: []
Index: []

In [60]:
import bokeh.io as io
import bokeh.models as models
import bokeh.plotting as plotting
import bokeh.resources as resources
import pandas as pd
from bokeh.models import ColumnDataSource
import math
from bokeh.io import output_notebook
import bokeh.palettes

# make the DF a column data source
source = ColumnDataSource(newdf) 

# figure object
launch_outer_plot = plotting.figure(x_range = newdf['team'].unique(),
    x_axis_label="Team",
    y_axis_label="Average Points",
    title= "Successes",
    tools = "hover", 
    tooltips = "@team $name: @$name",
    width=800, height=400)

# plot data
launch_outer_plot.vbar_stack(['upper_auto', 'upper_tele', 'lower_auto', 'lower_tele'],
                             x = 'team', 
                             color = bokeh.palettes.Paired[4][:], 
                             width = 0.9,
                             source = source,
                             legend_label = ['upper_auto', 'upper_tele', 'lower_auto', 'lower_tele'])
                            
# diagonal team names
launch_outer_plot.xaxis.major_label_orientation = math.pi/4
# display the plot
plotting.show(launch_outer_plot)

KeyError: 'team'

In [61]:
# make the DF a column data source
source = ColumnDataSource(newdf) 
colors = ["pink", "purple", "green", "yellow"]

# figure object
launch_outer_plot = plotting.figure(x_range = newdf['team'],
    x_axis_label="Team",
    y_axis_label="Average Points",
    title="Successes",
    tools = "hover", 
    tooltips = "@team $name: @$name",
    width=800, height=400)

# plot data
launch_outer_plot.vbar_stack(['upper_auto', 'lower_auto'],
                             x = 'team', 
                             color = bokeh.palettes.Category10[3][:2], 
                             width = 0.9,
                             source = source)
# diagonal team names
launch_outer_plot.xaxis.major_label_orientation = math.pi/4
# display the plot
plotting.show(launch_outer_plot)

KeyError: 'team'

In [62]:
measures

,match,measure1,measure2,measure_type,phase,task,team_number
0,qm1,left,-1,categorical,auto,start_pos,frc1294
1,qm1,1,-1,count,auto,pickup_field,frc1294
10,qm1,2,-1,count,tele,pickup-field,frc4512
100,qm1,0,-1,count,endgame,penalty_count,frc4915
1000,qm8,0,-1,count,endgame,penalty_count,frc949
...,...,...,...,...,...,...,...
995,qm8,0,0,count,auto,hp,frc949
996,qm8,0,-1,count,endgame,hangar_level_end,frc949
997,qm8,false,-1,boolean,endgame,fall_over,frc949
998,qm8,0,-1,count,endgame,hangar_level_start,frc949
999,qm8,0,0,count,tele,lower,frc949

In [63]:
measures = measures[measures.task == 'start_pos']
measures.drop(columns=['measure2'])

     match measure1 measure_type phase       task team_number
0      qm1     left  categorical  auto  start_pos     frc1294
1008   qm9     left  categorical  auto  start_pos     frc4512
1009   qm9    right  categorical  auto  start_pos     frc4911
1010   qm9   center  categorical  auto  start_pos     frc5683
1011   qm9   center  categorical  auto  start_pos      frc488
...    ...      ...          ...   ...        ...         ...
903    qm8     left  categorical  auto  start_pos     frc2929
905    qm8     left  categorical  auto  start_pos     frc4915
907    qm8    right  categorical  auto  start_pos      frc949
908    qm8   center  categorical  auto  start_pos     frc2928
910    qm8   center  categorical  auto  start_pos     frc4469

[367 rows x 6 columns]

In [64]:
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
data = {'fruits' : fruits,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 3, 2, 4, 6],
        '2017'   : [3, 2, 4, 4, 5, 3]}
data

{'fruits': ['Apples',
  'Pears',
  'Nectarines',
  'Plums',
  'Grapes',
  'Strawberries'],
 '2015': [2, 1, 4, 3, 2, 4],
 '2016': [5, 3, 3, 2, 4, 6],
 '2017': [3, 2, 4, 4, 5, 3]}

In [65]:
schedule

NameError: name 'schedule' is not defined

In [86]:
melted_measures = measures.melt(
            id_vars=["match", "team_number", "phase", "task", "measure_type"],
            value_vars=["measure1", "measure2"],
            var_name="measure_col")
        
counts = melted_measures[melted_measures.measure_type == "count"]
counts["value"] = pd.to_numeric(counts.value)
counts["value"] = counts.value.replace(0, np.nan)
        
means = counts.pivot_table(
            "value",
            index=["team_number", "task", "measure_col"],
            columns=["phase"])
means = means.fillna(0)

filtered = means.unstack(["task", "measure_col"])

In [93]:
melted_measures

    match team_number phase       task measure_type measure_col   value
0     qm1     frc1294  auto  start_pos  categorical    measure1    left
1     qm9     frc4512  auto  start_pos  categorical    measure1    left
2     qm9     frc4911  auto  start_pos  categorical    measure1   right
3     qm9     frc5683  auto  start_pos  categorical    measure1  center
4     qm9      frc488  auto  start_pos  categorical    measure1  center
..    ...         ...   ...        ...          ...         ...     ...
729   qm8     frc2929  auto  start_pos  categorical    measure2      -1
730   qm8     frc4915  auto  start_pos  categorical    measure2      -1
731   qm8      frc949  auto  start_pos  categorical    measure2      -1
732   qm8     frc2928  auto  start_pos  categorical    measure2      -1
733   qm8     frc4469  auto  start_pos  categorical    measure2      -1

[734 rows x 7 columns]

In [88]:
melted_measures[melted_measures.measure_type == "count"]

Empty DataFrame
Columns: [match, team_number, phase, task, measure_type, measure_col, value]
Index: []

In [73]:
import pandas as pd
import server.database as database
import pandas as pd
import bokeh.io as io
import bokeh.models as models 
from bokeh.models import MultiChoice
import bokeh.plotting as plotting
import bokeh.resources as resources
from bokeh.models import ColumnDataSource
import math
import bokeh.palettes
import numpy as np
from bokeh.layouts import column
import viewer.app.data as data

class CountPlot:
    def __init__(self, inittasks, alltasks):
        self.inittasks = inittasks
        self.alltasks = alltasks
        self.multi_choice = None
        self.layout = None

    def _callback(self, attr, old, new):
        if len(new) < 3:
            self.multi_choice.update(value=old)
        else:
            plot = self.graph_plot() 
            self.layout.children[0] = plot

    def get_layout(self): 
        self.multi_choice = MultiChoice(value=self.inittasks,
                                        options=self.alltasks)
        self.multi_choice.on_change("value", self._callback)
        self.layout = column([self.graph_plot(),
                              self.multi_choice])
        return self.layout
    
    def prepare_data(self, measuresdf):
        melted_measures = measuresdf.melt(
            id_vars=["match", "team_number", "phase", "task", "measure_type"],
            value_vars=["measure1", "measure2"],
            var_name="measure_col")
        
        counts = melted_measures[melted_measures.measure_type == "count"].copy()
        counts["value"] = pd.to_numeric(counts.value)
        counts["value"] = counts.value.replace(-1, np.nan)

        means = counts.pivot_table(
            "value",
            index=["team_number", "task", "measure_col"],
            columns=["phase"])
        means = means.fillna(0)

        filtered = means.unstack(["task", "measure_col"])
        cds = ColumnDataSource(filtered)
        return cds
    
        
    def graph_plot(self):
        measures = data.get_data()[0]
        filtered = self.prepare_data(measures)
        tasks = self.multi_choice.value
        plot = plotting.figure(
            x_range = np.unique(filtered.data["team_number"]),
            x_axis_label="Team",
            y_axis_label="Average Successes",
            title= "Successes",
            tools = "hover", 
            tooltips = "@team_number $name: @$name",
            width=1200, height=500)
        
        vbar = plot.vbar_stack(tasks,
                        x = "team_number", 
                        color = bokeh.palettes.Paired[len(tasks)], 
                        width = 0.9,
                        source = filtered)

        legend_items = [(lbl, [glyph]) for lbl, glyph in zip(tasks, vbar)]
        legend = models.Legend(items = legend_items, location = "top_right") 
        plot.add_layout(legend, 'right')

        plot.xaxis.major_label_orientation = math.pi/4
        return plot

In [74]:
means

Empty DataFrame
Columns: []
Index: []